AWSTemplateFormatVersion: '2010-09-09' 
# Specifies the AWS CloudFormation template version being used.

Description: >-
  CloudFormation template to create EC2 instance, assigns elastic IP and runs update and upgrade
  Also creates CloudWatch alarms for high CPU utilization and unauthorized access attempts.
# A description of the template's purpose.

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    # Defines an EC2 instance resource.
    Properties:
      AvailabilityZone: us-east-1a
      # Specifies the availability zone where the instance will be launched.
      ImageId: ami-04a81a99f5ec58529
      # Specifies the Amazon Machine Image (AMI) ID for the instance.
      InstanceType: t2.micro
      # Defines the type of EC2 instance (e.g., t2.micro for a lightweight instance).
      SecurityGroupIds:
        - sg-00c17b08a87a89bfb
        # Associates the instance with the specified security group to control inbound and outbound traffic.
      KeyName: githubactionsepa
      # Specifies the key pair name to allow SSH access to the instance.
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # User data script to execute commands on instance initialization.

          LOG_FILE="/var/log/script_execution.log"
          # Defines the log file location for the script's output.

          check_exit_status() {
              if [ $? -ne 0 ]; then
                  echo "Error: $1 failed." | tee -a $LOG_FILE
                  exit 1
              else
                  echo "$1 succeeded." | tee -a $LOG_FILE
              fi
          }
          # A helper function to check the exit status of commands and log the outcome.

          > $LOG_FILE
          # Clears any existing content in the log file.

          echo "Running apt update..." | tee -a $LOG_FILE
          sudo apt -y update
          check_exit_status "apt update"
          # Updates the package list on the instance and logs the outcome.

          echo "Running apt upgrade..." | tee -a $LOG_FILE
          sudo apt -y upgrade
          check_exit_status "apt upgrade"
          # Upgrades all installed packages to their latest versions and logs the outcome.

  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    # Defines a resource to associate an Elastic IP (EIP) with the EC2 instance.
    Properties:
      InstanceId: !Ref MyInstance
      # References the ID of the EC2 instance to associate with the EIP.
      AllocationId: eipalloc-0fcfaf56ef4f1f122
      # Specifies the allocation ID of the Elastic IP to associate.

  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    # Defines a CloudWatch alarm resource.
    Properties:
      AlarmName: HighCPUUtilizationAlarm
      # Specifies the name of the alarm.
      AlarmDescription: Alarm triggered when CPU utilization exceeds 80%.
      # Describes the purpose of the alarm.
      MetricName: CPUUtilization
      # Specifies the metric to monitor.
      Namespace: AWS/EC2
      # Defines the namespace of the metric.
      Statistic: Average
      # Specifies the statistic to evaluate (e.g., Average).
      Period: 300
      # Defines the evaluation period in seconds (e.g., 300 seconds = 5 minutes).
      EvaluationPeriods: 1
      # The number of periods over which data is compared to the threshold.
      Threshold: 80
      # The threshold value for triggering the alarm.
      ComparisonOperator: GreaterThanThreshold
      # Specifies the condition for triggering the alarm (e.g., GreaterThanThreshold).
      Dimensions:
        - Name: InstanceId
          Value: !Ref MyInstance
          # Monitors the specified EC2 instance.
      AlarmActions:
        - arn:aws:sns:us-east-1:772362934603:Default_CloudWatch_Alarms_Topic
        # The ARN of the SNS topic to notify when the alarm is triggered.

  UnauthorizedAccessAlarm:
    Type: AWS::CloudWatch::Alarm
    # Defines a CloudWatch alarm for unauthorized access attempts.
    Properties:
      AlarmName: UnauthorizedAccessAttemptsAlarm
      # Specifies the name of the alarm.
      AlarmDescription: Alarm triggered on any unauthorized access attempts.
      # Describes the purpose of the alarm.
      MetricName: UnauthorizedAccessAttempts
      # Specifies the metric to monitor.
      Namespace: AWS/EC2
      # Defines the namespace of the metric.
      Statistic: Sum
      # Specifies the statistic to evaluate (e.g., Sum of unauthorized attempts).
      Period: 300
      # Defines the evaluation period in seconds (e.g., 300 seconds = 5 minutes).
      EvaluationPeriods: 1
      # The number of periods over which data is compared to the threshold.
      Threshold: 1
      # The threshold value for triggering the alarm (e.g., any unauthorized attempt).
      ComparisonOperator: GreaterThanOrEqualToThreshold
      # Specifies the condition for triggering the alarm.
      Dimensions:
        - Name: InstanceId
          Value: !Ref MyInstance
          # Monitors the specified EC2 instance.
      AlarmActions:
        - arn:aws:sns:us-east-1:772362934603:Default_CloudWatch_Alarms_Topic
        # The ARN of the SNS topic to notify when the alarm is triggered.
