name: Test and Deploy Bash Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug SSH connection
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.MY_ELASTIC_IP }} "echo 'SSH Connection Successful'"

    - name: Add SSH Key and Generate Known Hosts
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.MY_ELASTIC_IP }} "
        mkdir -p ~/.ssh &&
        echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa &&
        chmod 600 ~/.ssh/id_rsa &&
        ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub &&
        ssh-keyscan github.com > ~/.ssh/known_hosts &&
        chmod 600 ~/.ssh/known_hosts"

    - name: Copy SSH Key to Root
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.MY_ELASTIC_IP }} "
        sudo mkdir -p /root/.ssh &&
        sudo cp ~/.ssh/id_rsa /root/.ssh/ &&
        sudo cp ~/.ssh/id_rsa.pub /root/.ssh/ &&
        sudo cp ~/.ssh/known_hosts /root/.ssh/ &&
        sudo chmod 600 /root/.ssh/id_rsa &&
        sudo chmod 600 /root/.ssh/known_hosts"

    - name: Remove Existing HTML Directory
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.MY_ELASTIC_IP }} "sudo rm -rf /var/www/html"

    - name: Run LEMP Setup
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.MY_ELASTIC_IP }} 'sudo sh /home/ubuntu/epa-project/lemp-setup.sh'

    - name: Run certbot install
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.MY_ELASTIC_IP }} 'sudo sh /home/ubuntu/epa-project/certbot-ssl-install.sh'

    - name: Run Wordpress install
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.MY_ELASTIC_IP }} 'sudo sh /home/ubuntu/epa-project/wordpress-install.sh'

    - name: Clone Git Repository as Root
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.MY_ELASTIC_IP }} 'sudo git clone git@github.com:kevwong16/wordpress-files.git /var/www/html'
